-- Login aanmaken
CREATE LOGIN ONLY_READ WITH PASSWORD = 'ISE'
GO

--Roles aanmaken
CREATE ROLE ONLY_READ_ROLE
GO

--Users aanmaken
CREATE USER ONLY_READ_USER FROM LOGIN ONLY_READ
GO

--Users toevoegen aan roles
ALTER ROLE ONLY_READ_ROLE ADD MEMBER ONLY_READ_USER
GO

--Rechten geven aan roles
GRANT SELECT ON CRS		TO ONLY_READ_ROLE
GRANT SELECT ON DEPT	TO ONLY_READ_ROLE
GRANT SELECT ON EMP		TO ONLY_READ_ROLE
GRANT SELECT ON GRD		TO ONLY_READ_ROLE
GRANT SELECT ON HIST	TO ONLY_READ_ROLE
GRANT SELECT ON MEMP	TO ONLY_READ_ROLE
GRANT SELECT ON OFFR	TO ONLY_READ_ROLE
GRANT SELECT ON REG		TO ONLY_READ_ROLE
GRANT SELECT ON SREP	TO ONLY_READ_ROLE
GRANT SELECT ON TERM	TO ONLY_READ_ROLE

GO

--ONLY_READ_USER testen
EXECUTE AS USER = 'ONLY_READ_USER'
GO

--Waardes toe proberen te voegen
BEGIN TRANSACTION

INSERT INTO EMP 
VALUES ( 9999, 'Test', 'Test', '1998-01-18', '2023-01-01', 6, 6500, 'TEST', 15)

ROLLBACK TRANSACTION

--Tabel proberen te lezen
SELECT *
FROM EMP

--Terug naar Admin
REVERT