ALTER TABLE DEPT
ADD CONSTRAINT dep_fk_emp FOREIGN KEY (mgr) REFERENCES EMP (empno)
ON UPDATE NO ACTION
ON DELETE NO ACTION

ALTER TABLE EMP
ADD CONSTRAINT emp_fk_grd FOREIGN KEY (sgrade) REFERENCES EMP (grade)
ON UPDATE CASCADE
ON DELETE NO ACTION

ALTER TABLE DEPT
ADD CONSTRAINT hst_fk_dep FOREIGN KEY (deptno) REFERENCES DEPT (deptno)
ON UPDATE NO ACTION
ON DELETE NO ACTION

ALTER TABLE DEPT
ADD CONSTRAINT hst_fk_emp FOREIGN KEY (empno) REFERENCES EMP (empno)
ON UPDATE NO ACTION
ON DELETE CASCADE

ALTER TABLE MEMP
ADD CONSTRAINT mmp_fk1_dep FOREIGN KEY (empno) REFERENCES EMP (empno)
ON UPDATE NO ACTION
ON DELETE NO ACTION

ALTER TABLE MEMP
ADD CONSTRAINT mmp_fk2_dep FOREIGN KEY (mgr) REFERENCES EMP (empno)
ON UPDATE NO ACTION
ON DELETE NO ACTION

ALTER TABLE OFFR
ADD CONSTRAINT ofr_fk_crs FOREIGN KEY (course) REFERENCES EMP (code)
ON UPDATE CASCADE
ON DELETE NO ACTION

ALTER TABLE OFFR
ADD CONSTRAINT ofr_fk_emp FOREIGN KEY (trainer) REFERENCES EMP (empno)
ON UPDATE NO ACTION
ON DELETE NO ACTION

ALTER TABLE REG
ADD CONSTRAINT reg_fk_emp FOREIGN KEY (stud) REFERENCES EMP (empno)
ON UPDATE NO ACTION
ON DELETE CASCADE

ALTER TABLE REG
ADD CONSTRAINT reg_fk_ofr FOREIGN KEY (course) REFERENCES EMP (course)
ON UPDATE NO ACTION
ON DELETE NO ACTION

ALTER TABLE SREP
ADD CONSTRAINT srp_fk_emp FOREIGN KEY (empno) REFERENCES EMP (empno)
ON UPDATE NO ACTION
ON DELETE CASCADE

ALTER TABLE TERM
ADD CONSTRAINT trm_fk_emp FOREIGN KEY (empno) REFERENCES EMP (empno)
ON UPDATE NO ACTION
ON DELETE CASCADE
